import React from 'react';
import './Home.css'

export default function PacienteTable(){

  return(
    <table class="blueTable">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Idade</th>
          <th>Diagnóstico</th>
          <th>Primeira Consulta</th>
          <th>Última Consulta</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>cell1_1</td>
          <td>cell2_1</td>
          <td>cell3_1</td>
          <td>cell4_1</td>
          <td>cell5_1</td>
        </tr>
        <tr>
          <td>cell1_2</td>
          <td>cell2_2</td>
          <td>cell3_2</td>
          <td>cell4_2</td>
          <td>cell5_2</td>
        </tr>
        <tr>
          <td>cell1_3</td>
          <td>cell2_3</td>
          <td>cell3_3</td>
          <td>cell4_3</td>
          <td>cell5_3</td>
        </tr>
        <tr>
          <td>cell1_4</td>
          <td>cell2_4</td>
          <td>cell3_4</td>
          <td>cell4_4</td>
          <td>cell5_4</td>
        </tr>
        <tr>
          <td>cell1_5</td>
          <td>cell2_5</td>
          <td>cell3_5</td>
          <td>cell4_5</td>
          <td>cell5_5</td>
        </tr>
        <tr>
          <td>cell1_6</td>
          <td>cell2_6</td>
          <td>cell3_6</td>
          <td>cell4_6</td>
          <td>cell5_6</td>
        </tr>
        <tr>
          <td>cell1_7</td>
          <td>cell2_7</td>
          <td>cell3_7</td>
          <td>cell4_7</td>
          <td>cell5_7</td>
        </tr>
        <tr>
          <td>cell1_8</td>
          <td>cell2_8</td>
          <td>cell3_8</td>
          <td>cell4_8</td>
          <td>cell5_8</td>
        </tr>
        <tr>
          <td>cell1_9</td>
          <td>cell2_9</td>
          <td>cell3_9</td>
          <td>cell4_9</td>
          <td>cell5_9</td>
        </tr>
        <tr>
          <td>cell1_10</td>
          <td>cell2_10</td>
          <td>cell3_10</td>
          <td>cell4_10</td>
          <td>cell5_10</td>
        </tr>
        <tr>
          <td>cell1_11</td>
          <td>cell2_11</td>
          <td>cell3_11</td>
          <td>cell4_11</td>
          <td>cell5_11</td>
        </tr>
        <tr>
          <td>cell1_12</td>
          <td>cell2_12</td>
          <td>cell3_12</td>
          <td>cell4_12</td>
          <td>cell5_12</td>
        </tr>
      </tbody>
    </table>
  );
}